name: Deploy Dev Network

on:
  push:
    paths:
      - 'modules/network/**'
      - 'environments/dev/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Configure AWS credentials (Dev)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws_access_key_deployment: ${{ secrets.AWS_ACCESS_KEY_DEPLOYMENT }}
          aws_secret_key_deployment: ${{ secrets.AWS_SECRET_KEY_DEPLOYMENT }}
          account_id: ${{ secrets.ACCOUNT_ID }}

      - name: Deploy Dev Environment
        run: |
          cd environments/dev
          terraform init
          terraform apply -auto-approve
