name: Deploy Dev Network

on:
  push:
    paths:
      - 'modules/**'
      - 'environments/dev/**'
      - '.github/workflows/deploy-network.yml'
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Configure AWS credentials (Dev)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_DEPLOYMENT }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_DEPLOYMENT }}
          aws-region: eu-central-1

      - name: Deploy Dev Environment
        run: |
          cd environments/dev
          terraform init -backend-config="region=${{ secrets.AWS_REGION_DEV }}"
          terraform plan -var="account_id=${{ secrets.AWS_ACCOUNT_ID }}" -var="db_username=${{ secrets.AWS_DB_USERNAME_DEV }}" -var="db_password=${{ secrets.AWS_DB_PASSWORD_DEV }}"
          terraform apply -auto-approve -var="account_id=${{ secrets.AWS_ACCOUNT_ID }}" -var="db_username=${{ secrets.AWS_DB_USERNAME_DEV }}" -var="db_password=${{ secrets.AWS_DB_PASSWORD_DEV }}"
